import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import React from "react";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Artistry Agora | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/artistryagora.png" />
      </Head>
      <section className="bg-navy text-light">
        <Navbar />
      </section>

      {/* ======= Contact Section ======= */}
      <section id="contact" className="contact py-5">
        <div className="container">
          <div className="text-center mb-5">
            <h2>Contact</h2>
            <p>
              Tersesat dalam tumpukan informasi? Jangan khawatir, kami di sini
              untuk membantu! Hubungi kami untuk mendapatkan solusi terbaik yang
              sesuai dengan kebutuhan Anda. Mari kita bangun jembatan komunikasi
              yang memperkaya dan memberi manfaat bagi semua.
            </p>
          </div>

          <div className="row">
            <div className="col-lg-5 d-flex align-items-stretch">
              <div className="info p-4 bg-light rounded">
                <div className="mb-4">
                  <i className="bi bi-geo-alt"></i>
                  <h4>Location :</h4>
                  <p>Jl. Pahlawan No. 1, example, example, Indonesia</p>
                </div>

                <div className="mb-4">
                  <i className="bi bi-envelope"></i>
                  <h4>Email :</h4>
                  <p>info@example.com</p>
                </div>

                <div className="mb-4">
                  <i className="bi bi-phone"></i>
                  <h4>Call:</h4>
                  <p>+1 5589 55488 55</p>
                </div>

                <iframe
                  src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d738.8298947933409!2d112.74474209461953!3d-7.26388206209248!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd7f92cdeef8595%3A0xd38a95482769b82c!2sAlun%20-%20Alun%20Surabaya!5e0!3m2!1sen!2sid!4v1718414954718!5m2!1sen!2sid"
                  style={{ border: 0, width: "100%", height: "290px" }}
                  allowfullscreen
                  loading="lazy"
                ></iframe>
              </div>
            </div>

            <div className="col-lg-7 mt-5 mt-lg-0 d-flex align-items-stretch">
              <form className="php-email-form w-100 bg-light p-4 rounded">
                <div className="row">
                  <div className="col-md-6 form-group">
                    <label htmlFor="name">Your Name</label>
                    <input
                      type="text"
                      name="name"
                      className="form-control"
                      id="name"
                      required
                    />
                  </div>
                  <div className="col-md-6 form-group mt-3 mt-md-0">
                    <label htmlFor="email">Your Email</label>
                    <input
                      type="email"
                      className="form-control"
                      name="email"
                      id="email"
                      required
                    />
                  </div>
                </div>
                <div className="form-group mt-3">
                  <label htmlFor="subject">Subject</label>
                  <input
                    type="text"
                    className="form-control"
                    name="subject"
                    id="subject"
                    required
                  />
                </div>
                <div className="form-group mt-3">
                  <label htmlFor="message">Message</label>
                  <textarea
                    className="form-control"
                    name="message"
                    rows="10"
                    required
                  ></textarea>
                </div>
                <div className="my-3">
                  <div className="loading">Loading</div>
                  <div className="error-message"></div>
                  <div className="sent-message">
                    Your message has been sent. Thank you!
                  </div>
                </div>
                <div className="text-center">
                  <button type="submit" className="btn btn-primary">
                    Send Message
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </section>
      {/* End Contact Section */}

      <Footer />
    </>
  );
}
