import CardAbout from "@/components/CardAbout";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import React from "react";

export default function About() {
  return (
    <>
      <Head>
        <title>Artistry Agora | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/artistryagora.png" />
      </Head>
      <section className="bg-navy text-light">
        <Navbar />
      </section>

      <CardAbout />

      <section className="bg-dark text-light">
        <Footer />
      </section>
    </>
  );
}
