import Brand from "@/components/Brand";
import CardEvent from "@/components/CardEvent";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
// import Statistics from "@/components/Statistics";
// import Stories from "@/components/Stories";
import { getData } from "@/utils/fetchData";
import Head from "next/head";

export default function index() {
  // console.log("data");
  // console.log(data);
  return (
    <>
      <Head>
        <title>Artistry Agora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="my-4">
        <Brand />
      </div>
      {/* <CardEvent data={data} title="Daftar Pameran" subTitle="Kesenian" /> */}
      {/* <Stories /> */}
      {/* <Statistics /> */}
      <Footer />
    </>
  );
}
